version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/takashabe/go-router

    steps:
      - checkout

      - run:
          name: Prepare
          command: |
            go get -u github.com/golang/dep/cmd/dep
            make deps

      - run:
          name: Run unit tests
          command: make test | tee ${TEST_RESULTS}/go-test.out
